version: '2'

services:
  sensor:
    build:
      context: sensor
      dockerfile: "Dockerfile${DOCKERFILE_SUFFIX}"
    ports:
      - "${SENSOR_API_HTTP_PORT}:3020"
    volumes:
      - "./sensor:/app"
    devices:
      - "${SENSOR_SERIAL_PORT}:/dev/ttyUSB0"

  api:
    build:
      context: api
      dockerfile: "Dockerfile${DOCKERFILE_SUFFIX}"
    volumes:
      - "./api:/app"

  spa:
    build:
      context: spa
      dockerfile: "Dockerfile${DOCKERFILE_SUFFIX}"
    ports:
      - "${SPA_HTTP_PORT}:8080"
    volumes:
      - "./spa:/app"
